services:
  web:
    build: .
    volumes:
      # Volume pour les fichiers statiques (partagé avec nginx)
      - static_volume:/app/staticfiles
      # Volume pour les fichiers médias (partagé avec nginx)
      # Ajustement pour utiliser /app/media au lieu de /app/mediafiles
      - media_volume:/app/media
      # Optionnel: Monter le code source pour le développement
      - .:/app
    # ports:
    #   - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    restart: always

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    restart: always

  nginx:
    image: nginx:stable-alpine
    ports:
      # Expose le port 80 de Nginx sur le port 80 de votre machine hôte
      - "80:80"
    volumes:
      # Monter la configuration Nginx
      - ./nginx.conf/default.conf:/etc/nginx/conf.d/default.conf
      # Partager le volume des fichiers statiques (lecture seule pour nginx)
      - static_volume:/app/staticfiles:ro
      # Partager le volume des fichiers médias (lecture seule pour nginx)
      # Ajustement pour utiliser /app/media au lieu de /app/mediafiles
      - media_volume:/app/media:ro
    depends_on:
      # S'assurer que le service web est démarré avant nginx
      - web
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume: